#!/bin/bash
#set -x


#simple stupid svn (compatible with 1.8.10 version) mock




function version() {
    echo "svn, version 1.8.10 (r1615264)
   compiled Aug 12 2014, 03:40:51 on x86_64-unknown-linux-gnu

Copyright (C) 2014 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.7
  - handles 'http' scheme
  - handles 'https' scheme
"
    return 0
}




function usage() {
    echo "Type 'svn help' for usage."
}




function help() {
    echo "usage: svn <subcommand> [options] [args]
Subversion command-line client.
Type 'svn help <subcommand>' for help on a specific subcommand.
Type 'svn --version' to see the program version and RA modules
  or 'svn --version --quiet' to see just the version number.

Most subcommands take file and/or directory arguments, recursing
on the directories.  If no arguments are supplied to such a
command, it recurses on the current directory (inclusive) by default.

Available subcommands:
   add
   auth
   blame (praise, annotate, ann)
   cat
   changelist (cl)
   checkout (co)
   cleanup
   commit (ci)
   copy (cp)
   delete (del, remove, rm)
   diff (di)
   export
   help (?, h)
   import
   info
   list (ls)
   lock
   log
   merge
   mergeinfo
   mkdir
   move (mv, rename, ren)
   patch
   propdel (pdel, pd)
   propedit (pedit, pe)
   propget (pget, pg)
   proplist (plist, pl)
   propset (pset, ps)
   relocate
   resolve
   resolved
   revert
   status (stat, st)
   switch (sw)
   unlock
   update (up)
   upgrade

Subversion is a tool for version control.
For additional information, see http://subversion.apache.org/
"
    return 0
}




function info() {
    echo "Path: .
Working Copy Root Path: /home/brand0m/bash_covr_example_svn
URL: https://github.com/brand0m/bash_covr_example
Relative URL: ^/
Repository Root: https://github.com/brand0m/bash_covr_example
Repository UUID: a1e7b279-acb7-1a1a-8285-ce57b7db7bff
Revision: 6
Node Kind: directory
Schedule: normal
Last Changed Author: brand0m
Last Changed Rev: 6
Last Changed Date: 2015-10-19 16:25:31 +0200 (Mon, 19 Oct 2015)
"
    return 0
}




function unknown_subcmd() {
    local readonly subcmd=${1}

    echo "Unknown subcommand: '${subcmd}'"
    usage
    return 1
}




function main() {
    #echo "1=${1}"
    #echo "2=${2}"

    if [ $# -eq 0 ] ; then
        usage
    else
        if [ "${1}" = "--version" ] ; then
            version
        elif [ "${1}" = "help" -o "${1}" = "--help" -o "${1}" = "-h" ] ; then
            help
        elif [ "${1}" = "info" ] ; then
            info
        else
            unknown_subcmd "${1}"
        fi
    fi

}




main "$@"

