#!/bin/bash
#set -x


#simple stupid svn (compatible with 1.8.10 version) mock




function usage() {
    echo "Type 'svn help' for usage."
}




function help() {
    echo "help..."
}




function unknown_subcmd() {
    local readonly subcmd=${1}

    echo "Unknown subcommand: '${subcmd}'"
    usage
}




function version() {
    echo "svn, version 1.8.10 (r1615264)
   compiled Aug 12 2014, 03:40:51 on x86_64-unknown-linux-gnu

Copyright (C) 2014 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.7
  - handles 'http' scheme
  - handles 'https' scheme
"
return 0
}




function main() {
    #echo "1=${1}"
    #echo "2=${2}"

    if [ $# -eq 0 ] ; then
        usage
    else
        if [ "${1}" = "--version" ] ; then
            version
        elif [ "${1}" = "--help" ] ; then
            help
        else
            unknown_subcmd "${1}"
        fi
    fi

}




main "$@"

